// Code generated by colgen v0.1.2; DO NOT EDIT.
package rpc

import (
	"apisrv/pkg/newsportal"
)

func NewCategories(in []newsportal.Category) []Category { return newsportal.MapP(in, NewCategory) }

func NewNewsList(in []newsportal.News) []News { return newsportal.MapP(in, NewNews) }

func NewNewsSummaries(in []newsportal.News) []NewsSummary { return newsportal.MapP(in, NewNewsSummary) }

func NewTags(in []newsportal.Tag) []Tag { return newsportal.MapP(in, NewTag) }

func NewUsers(in []newsportal.User) []User { return newsportal.MapP(in, NewUser) }
