// Code generated by zenrpc v2.2.12; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	NewsService struct{ News, GetById, CountNews, Categories, Tags, UserByID string }
}{
	NewsService: struct{ News, GetById, CountNews, Categories, Tags, UserByID string }{
		News:       "news",
		GetById:    "getbyid",
		CountNews:  "countnews",
		Categories: "categories",
		Tags:       "tags",
		UserByID:   "userbyid",
	},
}

func (NewsService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"News": {
				Description: `News return list news.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "params",
						Optional: true,
						Type:     smd.Object,
						TypeName: "QueryParams",
						Properties: smd.PropertyList{
							{
								Name: "CategoryId",
								Type: smd.Integer,
							},
							{
								Name: "TagId",
								Type: smd.Integer,
							},
							{
								Name: "PageSize",
								Type: smd.Integer,
							},
							{
								Name: "Page",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]NewsSummary",
					Items: map[string]string{
						"$ref": "#/definitions/NewsSummary",
					},
					Definitions: map[string]smd.Definition{
						"NewsSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "newsSummaryID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "publishedAt",
									Type: smd.String,
								},
								{
									Name:     "category",
									Optional: true,
									Ref:      "#/definitions/Category",
									Type:     smd.Object,
								},
								{
									Name: "tags",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/Tag",
									},
								},
							},
						},
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					200: "ok",
					404: "not found",
				},
			},
			"GetById": {
				Description: `GetById returns news by ID.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `news id`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "News",
					Properties: smd.PropertyList{
						{
							Name: "newsID",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name:     "content",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "author",
							Type: smd.String,
						},
						{
							Name:     "category",
							Optional: true,
							Ref:      "#/definitions/Category",
							Type:     smd.Object,
						},
						{
							Name: "tags",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Tag",
							},
						},
						{
							Name: "publishedAt",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					200: "ok",
					404: "not found",
				},
			},
			"CountNews": {
				Description: `CountNews returns count news by filters.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "params",
						Optional: true,
						Type:     smd.Object,
						TypeName: "QueryParams",
						Properties: smd.PropertyList{
							{
								Name: "CategoryId",
								Type: smd.Integer,
							},
							{
								Name: "TagId",
								Type: smd.Integer,
							},
							{
								Name: "PageSize",
								Type: smd.Integer,
							},
							{
								Name: "Page",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type: smd.Integer,
				},
				Errors: map[int]string{
					200: "ok",
					404: "not found",
				},
			},
			"Categories": {
				Description: `Categories return list category`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Category",
					Items: map[string]string{
						"$ref": "#/definitions/Category",
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					200: "ok",
					404: "not found",
				},
			},
			"Tags": {
				Description: `Tags return list tag.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Tag",
					Items: map[string]string{
						"$ref": "#/definitions/Tag",
					},
					Definitions: map[string]smd.Definition{
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					200: "ok",
					404: "not found",
				},
			},
			"UserByID": {
				Description: `User return user by id.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "id",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "User",
					Properties: smd.PropertyList{
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name:     "lastActivityAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					200: "ok",
					404: "not found",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s NewsService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.NewsService.News:
		var args = struct {
			Params *queryParams `json:"params"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"params"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.News(ctx, args.Params))

	case RPC.NewsService.GetById:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetById(ctx, args.Id))

	case RPC.NewsService.CountNews:
		var args = struct {
			Params *queryParams `json:"params"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"params"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.CountNews(ctx, args.Params))

	case RPC.NewsService.Categories:
		resp.Set(s.Categories(ctx))

	case RPC.NewsService.Tags:
		resp.Set(s.Tags(ctx))

	case RPC.NewsService.UserByID:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UserByID(ctx, args.Id))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
