[Server]
Host = "127.0.0.1"
Port = "8080"
ReadTimeout = "30s"
WriteTimeout = "30s"
ShutdownTimeout = "10s"

[Database]
Host = "localhost"
Port = "5432"
Database = "postgres"
User = "postgres"
Password = "postgres"